### ISSUE TITLE
Bot does not reconnect on server restart

### ISSUE THREAD

**Issue by hyperdefined** [starcraft66/minecraft-discord-bridge#62]
I've noticed that the bot doesn't connect back to the MC server once the server restarts. The bot shows online on Discord. My server does a daily restart and I have to restart the bot every time.
```
2019-10-14 22:04:12,469:bridge:ERROR:A minecraft exception occured! 'text':
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/minecraft-discord-bridge-ODfYI37s/lib/python3.7/site-packages/minecraft/networking/connection.py", line 544, in run
    self._run()
  File "/root/.local/share/virtualenvs/minecraft-discord-bridge-ODfYI37s/lib/python3.7/site-packages/minecraft/networking/connection.py", line 582, in _run
    self.connection._react(packet)
  File "/root/.local/share/virtualenvs/minecraft-discord-bridge-ODfYI37s/lib/python3.7/site-packages/minecraft/networking/connection.py", line 521, in _react
    listener.call_packet(packet)
  File "/root/.local/share/virtualenvs/minecraft-discord-bridge-ODfYI37s/lib/python3.7/site-packages/minecraft/networking/packets/packet_listener.py", line 15, in call_packet
    self.callback(packet)
  File "/DestroyMC/DiscordBridge/minecraft-discord-bridge/minecraft_discord_bridge/minecraft_discord_bridge.py", line 683, in handle_player_list_header_and_footer_update
    self.tab_header = json.loads(header_footer_packet.header)["text"]
KeyError: 'text'
2019-10-14 22:04:12,470:bridge:INFO:Disconnected.
2019-10-14 22:04:12,470:bridge:INFO:Forced a disconnection because the connection is still connected.
2019-10-14 22:04:27,520:bridge:INFO:Reconnecting.
2019-10-14 22:04:27,521:bridge:ERROR:A minecraft exception occured! 'NoneType' object has no attribute 'send':

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/minecraft-discord-bridge-ODfYI37s/lib/python3.7/site-packages/minecraft/networking/connection.py", line 544, in run
    self._run()
  File "/root/.local/share/virtualenvs/minecraft-discord-bridge-ODfYI37s/lib/python3.7/site-packages/minecraft/networking/connection.py", line 559, in _run
    while not self.interrupt and self.connection._pop_packet():
  File "/root/.local/share/virtualenvs/minecraft-discord-bridge-ODfYI37s/lib/python3.7/site-packages/minecraft/networking/connection.py", line 297, in _pop_packet
    self._write_packet(self._outgoing_packet_queue.popleft())
  File "/root/.local/share/virtualenvs/minecraft-discord-bridge-ODfYI37s/lib/python3.7/site-packages/minecraft/networking/connection.py", line 310, in _write_packet
    packet.write(self.socket)
  File "/root/.local/share/virtualenvs/minecraft-discord-bridge-ODfYI37s/lib/python3.7/site-packages/minecraft/networking/packets/packet.py", line 99, in write
    self._write_buffer(socket, packet_buffer, compression_threshold)
  File "/root/.local/share/virtualenvs/minecraft-discord-bridge-ODfYI37s/lib/python3.7/site-packages/minecraft/networking/packets/packet.py", line 88, in _write_buffer
    VarInt.send(len(packet_buffer.get_writable()), socket)  # Packet Size
  File "/root/.local/share/virtualenvs/minecraft-discord-bridge-ODfYI37s/lib/python3.7/site-packages/minecraft/networking/types/basic.py", line 165, in send
    socket.send(out)
AttributeError: 'NoneType' object has no attribute 'send'
2019-10-14 22:05:27,753:bridge:INFO:Disconnected.
```

**Comment by starcraft66** [comment]
Hey, I'm actually running into this problem myself. I think that this is an issue in the upstream library pyCraft but I will continue investigating. I already have plans to temporarily fix this by restarting the bot if it fails to reconnect too many times in a row as discussed in issue #59 until I find the root cause.

**Comment by starcraft66** [comment]
I also noticed that from what I can see in your crash log, the bot has crashed because it was unable to handle the text in your player tab list header. If you'd like me to look into that, please run the bridge with the log level set to "DEBUG" and open an issue with the stack trace next time this happens so that I can see exactly what data your server is sending to the bridge.

**Comment by starcraft66** [comment]
Please try the new reconnect failsafe feature and let me know if it fixes your issue. Please note that the bot will simply exit if it exceeds its threshold of failed server joins. A process supervisor like `systemd` or `docker` should be used to restart the bridge automatically when it exits.

**Comment by hyperdefined** [comment]
I tested with some of that changes. I run the service with systemd as a service. The error about the tab menu is the first issue that appears when the server restarts. But afterwards, there is an error when it tries to reconnect.

This is the error when the server first disconnects everyone on the restart:
```
2019-10-15 13:56:38,246:bridge:ERROR:A minecraft exception occured! 'text':
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/minecraft-discord-bridge-ODfYI37s/lib/python3.7/site-packages/minecraft/networking/connection.py", line 544, in run
    self._run()
  File "/root/.local/share/virtualenvs/minecraft-discord-bridge-ODfYI37s/lib/python3.7/site-packages/minecraft/networking/connection.py", line 582, in _run
    self.connection._react(packet)
  File "/root/.local/share/virtualenvs/minecraft-discord-bridge-ODfYI37s/lib/python3.7/site-packages/minecraft/networking/connection.py", line 521, in _react
    listener.call_packet(packet)
  File "/root/.local/share/virtualenvs/minecraft-discord-bridge-ODfYI37s/lib/python3.7/site-packages/minecraft/networking/packets/packet_listener.py", line 15, in call_packet
    self.callback(packet)
  File "/DestroyMC/DiscordBridge/minecraft-discord-bridge/minecraft_discord_bridge/minecraft_discord_bridge.py", line 709, in handle_player_list_header_and_footer_update
    self.tab_header = json.loads(header_footer_packet.header)["text"]
KeyError: 'text'
2019-10-15 13:56:38,247:bridge:INFO:Disconnected.
2019-10-15 13:56:38,247:bridge:INFO:Forced a disconnection because the connection is still connected.
```


This is the error that happens when it tries to reconnect with the changes:
```
2019-10-15 13:57:23,424:bridge:INFO:Reconnecting.
2019-10-15 13:57:23,424:bridge:ERROR:A minecraft exception occured! 'NoneType' object has no attribute 'send':
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/minecraft-discord-bridge-ODfYI37s/lib/python3.7/site-packages/minecraft/networking/connection.py", line 544, in run
    self._run()
  File "/root/.local/share/virtualenvs/minecraft-discord-bridge-ODfYI37s/lib/python3.7/site-packages/minecraft/networking/connection.py", line 559, in _run
    while not self.interrupt and self.connection._pop_packet():
  File "/root/.local/share/virtualenvs/minecraft-discord-bridge-ODfYI37s/lib/python3.7/site-packages/minecraft/networking/connection.py", line 297, in _pop_packet
    self._write_packet(self._outgoing_packet_queue.popleft())
  File "/root/.local/share/virtualenvs/minecraft-discord-bridge-ODfYI37s/lib/python3.7/site-packages/minecraft/networking/connection.py", line 310, in _write_packet
    packet.write(self.socket)
  File "/root/.local/share/virtualenvs/minecraft-discord-bridge-ODfYI37s/lib/python3.7/site-packages/minecraft/networking/packets/packet.py", line 99, in write
    self._write_buffer(socket, packet_buffer, compression_threshold)
  File "/root/.local/share/virtualenvs/minecraft-discord-bridge-ODfYI37s/lib/python3.7/site-packages/minecraft/networking/packets/packet.py", line 88, in _write_buffer
    VarInt.send(len(packet_buffer.get_writable()), socket)  # Packet Size
  File "/root/.local/share/virtualenvs/minecraft-discord-bridge-ODfYI37s/lib/python3.7/site-packages/minecraft/networking/types/basic.py", line 165, in send
    socket.send(out)
AttributeError: 'NoneType' object has no attribute 'send'
2019-10-15 13:57:23,425:bridge:INFO:Disconnected.
2019-10-15 13:57:23,425:bridge:INFO:Failed to join the server 3 times in a row. Exiting.
2019-10-15 13:57:23,425:bridge:INFO:Use a process supervisor if you wish to automatically restart the bridge.
2019-10-15 13:57:50,616:discord.gateway:INFO:Websocket closed with 1000 (), cannot reconnect.
```

**Comment by starcraft66** [comment]
>This is the error when the server first disconnects everyone on the restart:

Could you please open a seperate issue for this one and provide logs with the log level set to "DEBUG"?

>This is the error that happens when it tries to reconnect with the changes:

This log output looks normal, it appears that your supervisor is not restarting the service when it dies. Could you please provide me a copy of the systemd unit file you use to run the bridge?

**Comment by hyperdefined** [comment]
Is it safe to post the full log with DEBUG? I do notice my bot's token is there.

Here is my chatbridge.service file. ("/DestroyMC/DiscordBridge/minecraft-discord-bridge/" is where the bot files are.)
```
[Unit]
Description=DestroyMC Chat Bridge
After=multi-user.target
Conflicts=getty@tty1.service

[Service]
Type=simple
WorkingDirectory=/DestroyMC/DiscordBridge/minecraft-discord-bridge/
ExecStart=/usr/bin/python3.7 -m pipenv run python -m minecraft_discord_bridge
StandardInput=tty-force
Restart=on-failure
[Install]
WantedBy=multi-user.target
```

**Comment by starcraft66** [comment]
>Is it safe to post the full log with DEBUG? I do notice my bot's token is there.

Sorry I was unclear, I don't need the full log due to its sensitive nature. I just need a few lines before the crash, I just need to see the messages that look like `Got Tablist H/F Update: header=<a bunch of json>`.

**Comment by hyperdefined** [comment]
Moved to #64

**Comment by starcraft66** [comment]
I've identified the root cause of the issue, it is as I expected. The bridge always exits with a return code of `0` which is defined as a successful exit in the POSIX specification. Because your systemd unit only restarts the process `on-failure`, it doesn't restart the bridge because its return code is successful. I will push fix to make the bridge exit with a non-successful error code if the failsafe is tripped. This successfully fixes the issue in my resting environment.

**Comment by starcraft66** [comment]
Please try running the bridge with the `feature/return-codes` branch and let me know if it fixes your issue.

**Comment by hyperdefined** [comment]
It restarts correctly now. However, it still fails to connect 3 times. This is what triggers the service to restart now. It fails to connect from this error still:
> AttributeError: 'NoneType' object has no attribute 'send'

After it fails 3 times, service restarts no problem and it connects on the first try.

**Comment by starcraft66** [comment]
>I mean the bot "crashes" from my tab menu still and errors out 3 times. Then the service correctly restarts.

Perfect, that is the expected outcome at the moment. I can't really do anything about the
    AttributeError: 'NoneType' object has no attribute 'send'
until this issue is resolved upstream in pyCraft.

The reconnection failsafe is meant to keep the bot alive as much as possible despite the fact that it might crash.
