### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by Christian913cin** [starcraft66/minecraft-discord-bridge#91]
I am using `python -m pipenv run python -m minecraft_discord_bridge` and running it in command prompt and it gives me this code. 
`C:\Users\Christian>python -m pipenv run python -m minecraft_discord_bridge
Traceback (most recent call last):
  File "C:\python\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Christian\.virtualenvs\Christian-NC7_73H2\minecraft_discord_bridge\__main__.py", line 21, in <module>
    from minecraft_discord_bridge import minecraft_discord_bridge
  File "C:\Users\Christian\.virtualenvs\Christian-NC7_73H2\minecraft_discord_bridge\minecraft_discord_bridge.py", line 41, in <module>
    from requests import RequestException
ModuleNotFoundError: No module named 'requests'`

**Comment by starcraft66** [comment]
It looks like you didn't install the dependencies before running the bridge. Run `python -m pipenv install` first.
